#!/bash/bin
# We start from home
cd
# mkdir -p projects && cd projects/

# Build & install aurutils
git clone https://aur.archlinux.org/aurutils.git && cd aurutils/
makepkg -si

echo "IMPORTANT!"
echo "requirement to edit the pacman.conf file and allow our custom repo:"
echo .
echo "> sudo vim /etc/pacman.conf"
echo .
echo "When ready, run '. setup-aurutils-02'"

